# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run:
          name: update angular cli
          command: npm install -g @angular/cli
      - run:
          name: build the dist
          command: ng build
workflows:
  # Name the workflow "welcome"
  build-and-deploy:
    # Run the build job in its own container
    jobs:
      - build
