# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            sudo apt-get -y -qq update
      - run:
          name: run install and then build
          command: npm i && npm run build
      - deploy:
          name: deploy to AWS
          command: |
            aws s3 sync ./dist/
            s3://whointheworldislaurawebsite/ --delete
workflows:
  # Name the workflow "welcome"
  build-and-deploy:
    # Run the build job in its own container
    jobs:
      - build-and-deploy
